# Generated by Django 5.1.5 on 2025-02-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
