# Generated by Django 5.1.5 on 2025-02-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag_slug_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
